spring.application.name=result-frontend
server.port=8080

labotrack.backend.sample-api-url=${SAMPLE_API_URL:http://localhost:8081}
labotrack.backend.analysis-api-url=${ANALYSIS_API_URL:http://localhost:8082}

management.endpoints.web.exposure.include=health,info
