spring.application.name=sample-api
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/labotrack}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:labotrack}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:labotrack}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
